repos:
  - repo: https://github.com/pycqa/flake8
    rev: 5.0.4 # Замените на актуальную версию flake8
    hooks:
      - id: flake8

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.2 # Замените на актуальную версию mypy
    hooks:
      - id: mypy
